        update place set country = 'FR' where country = 'Pháp';
        update place set country = 'FR' where country = 'France';
        update place set country = 'US' where country = 'Hoa Kỳ';
        update place set country = 'CA' where country = 'Canada';
        update place set country = 'DE' where country = 'Đức';
        update place set country = 'BE' where country = 'Bỉ';
        update place set country = 'IT' where country = 'Ý';
        update place set country = 'ES' where country = 'Tây Ban Nha';
        update place set country = 'NL' where country = 'Hà Lan';
        update place set country = 'DK' where country = 'Đan Mạch';
        update place set country = 'TR' where country = 'Thổ Nhĩ Kỳ';
        update place set country = 'JP' where country = 'Nhật Bản';
        update place set country = 'CN' where country = 'Trung Quốc';
        update place set country = 'KR' where country = 'Hàn Quốc';
        update place set country = 'KR' where country = 'South Korea';
        update place set country = 'HK' where country = 'Hong Kong';
        update place set country = 'US' where country = 'United States';
        update place set country = 'SN' where country = 'Senegal';
        update place set country = 'RU' where country = 'Russia';
        update place set country = 'MA' where country = 'Morocco';
        update place set country = 'DZ' where country = 'Algeria';
        update place set country = 'MX' where country = 'Mexico';
        update place set country = 'AU' where country = 'Australia';
        update place set country = 'TW' where country = 'Taiwan';
        update place set country = 'NL' where country = 'Netherlands';
        update place set country = 'CZ' where country = 'Czech Republic';
        update place set country = 'AT' where country = 'Austria';
        update place set country = 'HU' where country = 'Hungary';
        update place set country = 'BE' where country = 'Belgium';
        update place set country = 'FI' where country = 'Finland';
        update place set country = 'DE' where country = 'Germany';
        update place set country = 'KH' where country = 'Cambodia';
        update place set country = 'AO' where country = 'Angola';
        update place set country = 'NG' where country = 'Nigeria';
        update place set country = 'VE' where country = 'Venezuela';
        update place set country = 'IL' where country = 'Israel';
        update place set country = 'EG' where country = 'Egypt';
        update place set country = 'JP' where country = 'Japan';
        update place set country = 'GR' where country = 'Greece';
        update place set country = 'VN' where country = 'Vietnam';
        update place set country = 'AR' where country = 'Argentina';
        update place set country = 'CH' where country = 'Switzerland';